# Generated by Django 6.0.3 on 2026-04-05 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lon', models.FloatField(blank=True, null=True)),
                ('drop_lat', models.FloatField(blank=True, null=True)),
                ('drop_lon', models.FloatField(blank=True, null=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='core.ride')),
            ],
        ),
    ]
